version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "8001:5432"
    volumes:
      - C:PATH TO FOLDER:/FOLDER NAME
    environment:
      POSTGRES_USER: YOUR USER
      POSTGRES_PASSWORD: YOUR PASSWORD
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: YOURUSER@EMAIL.COM
      PGADMIN_DEFAULT_PASSWORD: YOUR PASSWORD